### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by germanfr** [armonia-is/manager#2]
A list of things to be done. If you don't know what to do this is the place to start looking at. Fill the checkboxes when anything's done.
- [x] Fill controller methods.
- [x] Main class.
- [x] Table models.
- Swing view:
  - [x] Confirmation prompt before exit, with an option to save.
  - [x] Buttons' action events.
    - [x] Delete all selected + enable/disable button
    - [x] Add new instrument.
    - [x] Edit items in the list.
  - [x] Error dialogs.
  - [x] Details dialog needs a little bit more work.
  - [x] Add price column to orders table.
  - [x] [Fix € Symbol in details dialog](https://github.com/armonia-is/manager/issues/1)

**Comment by germanfr** [comment]
@azaferna @galons01 @Kadaiser

**Comment by azaferna** [comment]
@johnbyrs
